# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 沐青桦的随笔
email: mutsinghua@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  分享生活，科技，投资的个人博客，用 Jekyll + GitHub Pages 搭建～
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zoudifei.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: "沐青桦"
github_username:  zoudifei

social:
  name: zoudifei.com  # 这里修改为你的名称
  links:
    - https://www.zoudifei.com  # 可选，版权信息中的链接
  email: mutsinghua@gmail.com
lang: zh-CN

# _config.yml
tabs:
  - name: categories          # 分类列表 Tab
    icon: fas fa-folder # 分类图标
    url: /categories/   # 分类列表页路径（需与分类页面 permalink 一致）
    order: 2

  - name: tag         # 标签列表 Tab（可选，与分类搭配使用）
    icon: fas fa-tags
    url: /tags/
    order: 3

  - name: archives         # 标签列表 Tab（可选，与分类搭配使用）
    icon: fas fa-archives
    url: /archives/
    order: 4

  - name: about
    icon: fas fa-user
    url: /about/
    order: 5

timezone: Asia/Shanghai

tag_path: /tags
# Build settings
remote_theme: cotes2020/jekyll-theme-chirpy@v6.5.5
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-archives  # 启用插件

avatar: /assets/img/avatar.jpg
favicon:
  small: /assets/img/favicons/favicon-small.png  # 小尺寸图标
  medium: /assets/img/favicons/favicon-small.png # 中尺寸图标
  large: /assets/img/favicons/favicon-mid.png  # 大尺寸图标
   
paginate: 10          # 首页每页显示 10 篇文章（可自定义）
paginate_path: "/page:num/"  # 分页路径（固定格式，不要改）

jekyll-archives:
  enabled:
    - tags  # 只生成标签页（如需分类页可加 categories）
    - categories
  layouts:  # 注意：这里是复数 layouts，不是单数 layout！
    tag: tag       # 标签页使用 _layouts/tag.html 布局
    category: category  # 分类页使用 _layouts/category.html 布局
  permalinks:
    tag: '/tags/:name/'  # 标签页的 URL 格式，需与链接路径一致
    category: '/categories/:name/' 
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
